globalThis.sanitizeAttr = function(str) {
  return str.replaceAll(':', 'i')
    .replaceAll('.', 'o')
    .replaceAll('+', 't')
    .replaceAll('>', 'v')
    .replaceAll('<', 'v')
    .replaceAll('~', 's')
    .replaceAll('|', '1')
    .replaceAll('(', 'l')
    .replaceAll(')', 'l')
    .replaceAll('[', 'I')
    .replaceAll(']', 'I')
    .replaceAll('=', '-')
    .replaceAll('$', 'S')
    .replaceAll('^', 'A')
    .replaceAll(';', 'j')
    .replaceAll('*', 'x')
    .replaceAll('/', 'X')
    .replaceAll('\\', 'X')
    .replaceAll('%', 'X')
    .replaceAll('&', '8')
    .replaceAll('@', 'a')
    .replaceAll('?', '7')
    .replaceAll('!', 'E')
    .replaceAll('#', 'H')
    .replaceAll('{', 'Q')
    .replaceAll('}', 'Q')
    .replaceAll('"', '2q')
    .replaceAll("'", 'q')
    .replaceAll(',', 'g')
    .replace(/\s/g, '_')
    .replace(/[^a-zA-Z0-9_-]/g, '�');
}